### ISSUE TITLE
rprompt for redis exec

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#92]
Then the user will know he is in a transection.

- [x] Display transaction state with rprompt;
- [ ] Render EXEC response with original command, not just command result.
- [x] Set transaction back to False on proper time. (see [here](https://github.com/laixintao/iredis/pull/118#issuecomment-526650137))
- [x] All command needs to render QUEUE in transation state.
- [ ] testcases...
- [ ] bugfix: abort transaction on Exception.

**Comment by guoweikuang** [comment]
![屏幕快照 2019-08-27 下午8 33 39](https://user-images.githubusercontent.com/12684035/63771578-04450980-c90a-11e9-8449-f31d07ee53ef.png)
like this?

**Comment by laixintao** [comment]
Sorry, I need to make myself clear.

I mean prompt_toolkit's rprompt:

![image](https://user-images.githubusercontent.com/9675939/63771884-9816d580-c90a-11e9-8b75-1eb01a845596.png)

You can find the example code here:

https://github.com/prompt-toolkit/python-prompt-toolkit/blob/2970d29936296349feb84aadb4217e1b9d57e2d3/examples/prompts/rprompt.py#L1

**Comment by guoweikuang** [comment]
@laixintao  I understand it wrong. 
I don't know much about the prompt-toolkit, I need to look at the documentation.

**Comment by laixintao** [comment]
I do not know it very mush either.

You can start here: https://python-prompt-toolkit.readthedocs.io/en/master/pages/getting_started.html

Then try the example code from the repo and see what can you do with it:

https://github.com/prompt-toolkit/python-prompt-toolkit/tree/master/examples

Also, this project is inspired by [mycli](https://github.com/dbcli/mycli)/[pgcli](https://github.com/dbcli/pgcli), I still get ideas from those projects.

**Comment by guoweikuang** [comment]
<img width="723" alt="屏幕快照 2019-08-27 下午9 39 19" src="https://user-images.githubusercontent.com/12684035/63776032-2727eb80-c913-11e9-9630-583a33d9eacd.png">

I implemented a simple version and didn't know if it was met.

**Comment by laixintao** [comment]
Yes, but let's change the prompt text from `multi` to `transaction`, multi just a redis command, and transaction is a redis' concept.

**Comment by laixintao** [comment]
FYI: the docs: https://redis.io/topics/transactions

I am still not sure the transaction state migrate was correct after my refactoring.

**Comment by guoweikuang** [comment]
`Render EXEC response with original command, not just command result.` 

@laixintao  I am thinking about a problem. Is it really necessary to return the original command and result after the exec command? How to display it is a problem. If the original command is too long, the display aspect is not beautiful.

```
May be this display mode, a command returns the result with the command
1) get hello
result
2) incr user
4
```

**Comment by laixintao** [comment]
Yes, it is exaclly my original idea. (acutally I mentioned it on slack)

```
1) set foo bar
OK
2) get foo
"bar"
```

**Comment by laixintao** [comment]
I think abort transaction on syntax error is correct now:

```
➜ [iredis] iredis git:(transaction-render) iredis
127.0.0.1:6379> multi
(error)
127.0.0.1:6379> get hello                          <transaction>
QUEUED
127.0.0.1:6379> get foo                            <transaction>
QUEUED
127.0.0.1:6379> get bar 1                          <transaction>
(error) wrong number of arguments for 'get' command
127.0.0.1:6379> exec                               <transaction>
(error) Transaction discarded because of previous errors.
127.0.0.1:6379> exec
(error) EXEC without MULTI
127.0.0.1:6379>
```

redis-cli:

```
➜  iredis git:(string-command) redis-cli
127.0.0.1:6379> mutli
(error) ERR unknown command `mutli`, with args beginning with:
127.0.0.1:6379> multi
OK
127.0.0.1:6379> get foo
QUEUED
127.0.0.1:6379> get bar
QUEUED
127.0.0.1:6379> get foo bar
(error) ERR wrong number of arguments for 'get' command
127.0.0.1:6379> exec
(error) EXECABORT Transaction discarded because of previous errors.
```
